### ISSUE TITLE
Cutout issues and requests

### ISSUE THREAD

**Issue by pllim** [spacetelescope/astroimtools#33]
Moved over from MOSViz issues:
- [ ] Plot cutout with labels in arcsec (spacetelescope/mosviz#19)
- [x] Better RGB image examples (spacetelescope/mosviz#20) -- #34, #35
- [x] `lupton_rgb.makeRGB()` arguments (spacetelescope/mosviz#23) -- resolved in sprint tag-ups
